In [1]:
import numpy as np

In [9]:
a=np.array([[[1, 2,3], [3, 4,3],[1,2,3]], [[5, 6,3], [7, 8,3],[1,2,3]]])
a.shape

(2, 3, 3)

In [15]:
b=np.arange(34,112,6)
b

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106])

In [18]:
c=np.linspace(50,500,91 ,dtype=int)
c

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [24]:
d=np.logspace(2,5,8 ,dtype=int)
d

array([   100,    268,    719,   1930,   5179,  13894,  37275, 100000])

In [27]:
e=np.arange(9)
e.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.zeros((6, 6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [48]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [51]:
t=np.zeros((8,8),dtype=int)
for i in range(8):
    t[i][i]=1
    
t

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [53]:
y=np.diag([3,0,0,0,0])
y

array([[3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [56]:
np.random.random(6)

array([0.59828146, 0.2339674 , 0.34176352, 0.12973118, 0.96894728,
       0.21113283])

In [58]:
u=np.random.randint(50,101, size=(5,2))
u

array([[96, 80],
       [75, 53],
       [89, 73],
       [90, 91],
       [62, 84]])

In [61]:
np.random.randint(50,101 ,size=(2,5,5))

array([[[58, 56, 51, 83, 69],
        [53, 74, 85, 72, 54],
        [66, 66, 94, 63, 62],
        [69, 52, 96, 57, 96],
        [64, 91, 91, 95, 68]],

       [[95, 89, 72, 84, 77],
        [93, 76, 56, 86, 77],
        [83, 84, 64, 80, 63],
        [64, 87, 60, 93, 75],
        [76, 73, 64, 99, 89]]])

In [63]:
i=np.random.randint(0,101,10)
print(i)
print(np.max(i))
print(np.min(i))

[ 53  29 100  29  74  56  41  73  92   8]
100
8


In [66]:
o=np.arange(51)
o[20:36]=500
o

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])